server:
  port: 33034
  servlet:
    context-path: /api
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB

config:
  shellpath: shell
  git:
    url: https://github.com/Tunerred/
    username: Tunerred
    password: fake

local:
  url: localhost
  username: test
  password: jiami
  gitpath: /home/yncs/git


# email (use -D to set)
##QQ smtp.qq.com
##sina smtp.sina.cn
##aliyun smtp.aliyun.com
##163 smtp.163.com
##126 smtp.126.com
#spring:
#  mail:
#    host: smtp.126.com
#    username: test@126.com
#    password: test
#    default-encoding: UTF-8
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/regulation?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.shelltest.service.entity

#showSql
logging:
  level:
    org:
      shelltest:
        service: debug

# INFO ENDPOINT CONFIGURATION
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@


##jwt配置
token:
  config:
    # 密钥
    secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
    # JWT的签发主体，存入issuer
    iss: deploy49server
    # 过期时间，时间戳
    # expiresSecond: 259200
    expiresSeconds: 10
    expiresMinutes: 100
